# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0baa7ff4116f1dd06d51c4622cba811d9f140eee126024bd2dbd3cee6f2dd103aec1d61ef85ffb2b3af8a5824254d3ba7b931ea1b1f831325cc06113d87ed0b2

test:
  secret_key_base: 4a2bbd5b360fb45ebc148165a785a216a479e7b780a089f7f33675fc847f92b437054f6ef60d07d26c4e7906f29a60b01d7e8dee7398ab4fc395c25f350946a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
